# Generated by Django 4.1 on 2022-09-09 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_all', models.FloatField()),
                ('received_all', models.FloatField()),
                ('produced_all', models.FloatField()),
                ('sent', models.FloatField(blank=True, default=0)),
                ('received', models.FloatField(blank=True, default=0)),
                ('produced', models.FloatField(blank=True, default=0)),
                ('autoconsumption', models.FloatField(blank=True, default=0)),
                ('consumption', models.FloatField(blank=True, default=0)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
