# Generated by Django 4.1 on 2022-08-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='recieved',
            new_name='received',
        ),
    ]
