# Generated by Django 4.1 on 2022-09-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_autoconsumption_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='energy_surplus',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='autoconsumption',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='autoconsumption_percentage',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='consumption',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='consumption_average',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
    ]
