# Generated by Django 4.1 on 2022-09-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_energy_surplus_alter_post_autoconsumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='produced_all',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='received_all',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='sent_all',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
