# Generated by Django 4.1 on 2022-09-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_produced_alter_post_produced_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='energy_surplus_cash',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
    ]
