# Generated by Django 4.1 on 2022-09-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_energy_surplus_cash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='energy_surplus_cash',
            new_name='balance',
        ),
    ]
