# Generated by Django 4.1 on 2022-09-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_energy_surplus_cash_post_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autoconsumption',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Autoconsumption (kW)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='autoconsumption_percentage',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Autoconsumption average (%)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='balance',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Balance (PLN)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='consumption',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Consumption (kW)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='consumption_average',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Consumption average (kW/day)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='energy_surplus',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Energy surplus (kW)'),
        ),
    ]
