# Generated by Django 4.1 on 2022-09-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_produced_alter_post_produced_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='produced_all',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
