# Generated by Django 4.1 on 2022-09-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_produced_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_funds',
            field=models.FloatField(blank=True, default=0, editable=False, verbose_name='Saved funds (PLN)'),
        ),
    ]
