# Generated by Django 4.1 on 2022-09-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='rules',
            field=models.CharField(choices=[('billing', 'Net-Billing (nowe zasady)'), ('metering', 'Net-Metering (stare zasady)')], default='metering', max_length=50, verbose_name='PV billing rules'),
        ),
    ]
