# Generated by Django 4.1 on 2022-09-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0003_alter_userconfig_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='produced_start',
            field=models.FloatField(default=0, verbose_name='Produced starting value (inverter)'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='received_start',
            field=models.FloatField(default=0, verbose_name='Received starting value (1.8.0)'),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='sent_start',
            field=models.FloatField(default=0, verbose_name='Sent starting value (2.8.0)'),
        ),
    ]
