# Generated by Django 4.1 on 2022-09-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0004_userconfig_produced_start_userconfig_received_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='energy_price',
            field=models.FloatField(default=0.8, verbose_name='Price for 1kWh (PLN)'),
        ),
    ]
