# Generated by Django 4.1 on 2022-09-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0005_userconfig_energy_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfig',
            old_name='energy_price',
            new_name='energy_buy_price',
        ),
    ]
