# Generated by Django 4.1 on 2022-09-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0007_userconfig_energy_sell_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='energy_sell_price',
            field=models.FloatField(default=0.8, verbose_name='Selling price for 1kWh (PLN)'),
        ),
    ]
