# Generated by Django 4.1 on 2022-09-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0008_alter_userconfig_energy_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='settlement_period',
            field=models.IntegerField(choices=[(1, '1 month'), (2, '2 months'), (6, '6 months'), (12, '12 months')], default=6),
        ),
    ]
