# Generated by Django 4.1 on 2022-09-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0009_userconfig_settlement_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='settlement_month',
            field=models.IntegerField(default=6, verbose_name='First month of settlement (1-12)'),
        ),
    ]
