# Generated by Django 4.1 on 2022-09-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0010_alter_userconfig_settlement_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='produced_input',
            field=models.CharField(choices=[('all', 'All time'), ('month', 'Month')], default='all', max_length=5),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='received_input',
            field=models.CharField(choices=[('all', 'All time'), ('month', 'Month')], default='all', max_length=5),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='sent_input',
            field=models.CharField(choices=[('all', 'All time'), ('month', 'Month')], default='all', max_length=5),
        ),
    ]
